(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const KEY = 'field-ops-track-log-v1';
  const R = 6371008.8;
  const sample = [
    { lat: 40.4168, lng: -3.7038, accuracy: 8, altitude: 650, speed: 1.2, timestamp: '2026-01-01T09:00:00.000Z' },
    { lat: 40.4175, lng: -3.7028, accuracy: 7, altitude: 651, speed: 1.4, timestamp: '2026-01-01T09:01:00.000Z' },
    { lat: 40.4184, lng: -3.7015, accuracy: 9, altitude: 652, speed: 1.3, timestamp: '2026-01-01T09:02:00.000Z' },
    { lat: 40.4191, lng: -3.7002, accuracy: 10, altitude: 653, speed: 1.1, timestamp: '2026-01-01T09:03:00.000Z' }
  ];
  function loadSaved() { try { const saved = JSON.parse(localStorage.getItem(KEY) || '{}'); return saved && typeof saved === 'object' ? saved : {}; } catch { return {}; } }
  const saved = loadSaved();
  const state = { points: Array.isArray(saved.points) ? saved.points : [], watchId: null, startedAt: saved.startedAt || null, lastStartedAt: null, activeMs: Number(saved.activeMs) || 0, map: null, line: null, markers: [] };
  function persist() { localStorage.setItem(KEY, JSON.stringify({ points: state.points, activeMs: elapsedMs(), startedAt: state.startedAt })); }
  function esc(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char])); }
  function xmlEscape(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&apos;' }[char])); }
  function number(value) { const result = Number(value); return Number.isFinite(result) ? result : null; }
  function haversine(a, b) { const lat1 = a.lat * Math.PI / 180, lat2 = b.lat * Math.PI / 180, dLat = (b.lat - a.lat) * Math.PI / 180, dLon = (b.lng - a.lng) * Math.PI / 180; const x = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2; return 2 * R * Math.asin(Math.sqrt(Math.min(1, x))); }
  function distance() { return state.points.slice(1).reduce((sum, point, index) => sum + haversine(state.points[index], point), 0); }
  function elapsedMs() { return state.activeMs + (state.lastStartedAt ? Date.now() - state.lastStartedAt : 0); }
  function duration(ms) { const total = Math.max(0, Math.floor(ms / 1000)); return [Math.floor(total / 3600), Math.floor(total % 3600 / 60), total % 60].map((value) => String(value).padStart(2, '0')).join(':'); }
  function formatDistance(meters) { return meters >= 1000 ? `${(meters / 1000).toLocaleString('es-ES', { maximumFractionDigits: 2 })} km` : `${meters.toLocaleString('es-ES', { maximumFractionDigits: 1 })} m`; }
  function setStatus(text, kind = 'idle') { $('status').textContent = text; $('statusBadge').textContent = kind === 'live' ? 'Grabando' : kind === 'paused' ? 'Pausado' : kind === 'error' ? 'Error' : 'En espera'; $('statusBadge').className = `badge ${kind}`; }
  function initMap() { if (!window.L) { $('mapFallback').hidden = false; return; } state.map = L.map('map', { minZoom: 1, maxZoom: 19 }).setView([40.4, -3.7], 5); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '© OpenStreetMap contributors', maxZoom: 19 }).addTo(state.map); renderMap(); }
  function renderMap() { if (!state.map) return; if (state.line) state.line.remove(); state.markers.forEach((marker) => marker.remove()); state.markers = []; if (!state.points.length) return; const latLngs = state.points.map((point) => [point.lat, point.lng]); state.line = L.polyline(latLngs, { color: '#d4ec83', weight: 5, opacity: .85 }).addTo(state.map); const start = L.circleMarker(latLngs[0], { radius: 7, color: '#10150f', fillColor: '#9dd7d1', fillOpacity: 1, weight: 2 }).bindTooltip('Inicio'); const end = L.circleMarker(latLngs.at(-1), { radius: 7, color: '#10150f', fillColor: '#d4ec83', fillOpacity: 1, weight: 2 }).bindTooltip('Último punto'); start.addTo(state.map); end.addTo(state.map); state.markers.push(start, end); const bounds = state.line.getBounds(); if (bounds.isValid()) state.map.fitBounds(bounds, { padding: [24, 24], maxZoom: 17 }); setTimeout(() => state.map.invalidateSize(), 100); }
  function renderTable() { $('pointHint').textContent = state.points.length ? `${state.points.length} puntos conservados` : '—'; $('pointTable').innerHTML = state.points.length ? `<table><thead><tr><th>Hora</th><th>Latitud</th><th>Longitud</th><th>Precisión</th><th>Altitud</th><th>Velocidad</th></tr></thead><tbody>${state.points.slice(-12).reverse().map((point) => `<tr><td>${esc(new Date(point.timestamp).toLocaleTimeString('es-ES'))}</td><td>${point.lat.toFixed(7)}</td><td>${point.lng.toFixed(7)}</td><td>${point.accuracy == null ? '—' : `${point.accuracy.toFixed(1)} m`}</td><td>${point.altitude == null ? '—' : `${point.altitude.toFixed(1)} m`}</td><td>${point.speed == null ? '—' : `${(point.speed * 3.6).toFixed(1)} km/h`}</td></tr>`).join('')}</tbody></table>` : '<p class="hint">No hay puntos aceptados. Inicia el GPS o carga el ejemplo para revisar el flujo.</p>'; }
  function render() { const meters = distance(); const ms = elapsedMs(); $('pointCount').textContent = String(state.points.length); $('distance').textContent = formatDistance(meters); $('duration').textContent = duration(ms); $('avgSpeed').textContent = ms > 0 ? `${(meters / (ms / 3600000) / 1000).toLocaleString('es-ES', { maximumFractionDigits: 2 })} km/h` : '0 km/h'; const latest = state.points.at(-1); $('accuracy').textContent = latest?.accuracy == null ? '—' : `${latest.accuracy.toFixed(1)} m`; $('mapHint').textContent = state.points.length ? `${formatDistance(meters)} · ${state.points.length} puntos` : 'Sin puntos'; renderTable(); renderMap(); persist(); }
  function readSettings() { return { minDistance: Math.max(0, number($('minDistance').value) ?? 5), maxAccuracy: Math.max(1, number($('maxAccuracy').value) ?? 100) }; }
  function acceptPosition(position) { const coords = position.coords; const lat = number(coords.latitude), lng = number(coords.longitude), accuracy = number(coords.accuracy); if (lat == null || lng == null || Math.abs(lat) > 90 || Math.abs(lng) > 180) return; const settings = readSettings(); if (accuracy != null && accuracy > settings.maxAccuracy) { setStatus(`Posición descartada: precisión ${accuracy.toFixed(1)} m supera el límite de ${settings.maxAccuracy} m.`, 'paused'); return; } const point = { lat, lng, accuracy, altitude: number(coords.altitude), speed: number(coords.speed), timestamp: new Date(position.timestamp || Date.now()).toISOString() }; const previous = state.points.at(-1); if (previous && haversine(previous, point) < settings.minDistance) return; state.points.push(point); render(); setStatus(`Punto aceptado · ${point.lat.toFixed(6)}, ${point.lng.toFixed(6)}`, 'live'); }
  function start() { if (!navigator.geolocation) { setStatus('Este navegador no ofrece geolocalización.', 'error'); return; } if (state.watchId != null) return; state.lastStartedAt = Date.now(); if (!state.startedAt) state.startedAt = new Date().toISOString(); state.watchId = navigator.geolocation.watchPosition(acceptPosition, (error) => setStatus(`GPS: ${error.message}`, 'error'), { enableHighAccuracy: true, maximumAge: 5000, timeout: 15000 }); $('startBtn').disabled = true; $('pauseBtn').disabled = false; setStatus('Solicitando posiciones GPS…', 'live'); render(); }
  function pause() { if (state.watchId != null) navigator.geolocation.clearWatch(state.watchId); state.watchId = null; state.activeMs += state.lastStartedAt ? Date.now() - state.lastStartedAt : 0; state.lastStartedAt = null; $('startBtn').disabled = false; $('pauseBtn').disabled = true; setStatus('Recorrido pausado. Puedes reanudarlo sin perder puntos.', 'paused'); render(); }
  function addExample() { pause(); state.points = sample.map((point) => ({ ...point })); state.activeMs = 180000; state.startedAt = sample[0].timestamp; state.lastStartedAt = null; render(); setStatus('Ejemplo cargado localmente. Revisa las exportaciones o inicia un recorrido nuevo.', 'paused'); }
  function download(filename, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
  function geojson() { const line = { type: 'Feature', properties: { name: 'Track Log', startedAt: state.startedAt, pointCount: state.points.length, distanceM: Number(distance().toFixed(2)) }, geometry: { type: 'LineString', coordinates: state.points.map((point) => [point.lng, point.lat, ...(point.altitude == null ? [] : [point.altitude])]) } }; const points = state.points.map((point, index) => ({ type: 'Feature', properties: { index: index + 1, timestamp: point.timestamp, accuracyM: point.accuracy, speedMps: point.speed }, geometry: { type: 'Point', coordinates: [point.lng, point.lat, ...(point.altitude == null ? [] : [point.altitude])] } })); return { type: 'FeatureCollection', features: state.points.length > 1 ? [line, ...points] : points }; }
  function gpx() { const points = state.points.map((point) => `<trkpt lat="${point.lat}" lon="${point.lng}">${point.altitude == null ? '' : `<ele>${point.altitude}</ele>`}<time>${xmlEscape(point.timestamp)}</time>${point.speed == null ? '' : `<extensions><speed>${point.speed}</speed></extensions>`}</trkpt>`).join(''); return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Field Ops Track Log" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>Track Log</name><time>${xmlEscape(state.startedAt || new Date().toISOString())}</time></metadata><trk><name>Track Log</name><trkseg>${points}</trkseg></trk></gpx>`; }
  function csv() { const rows = [['index','timestamp','latitude','longitude','accuracy_m','altitude_m','speed_mps'], ...state.points.map((point, index) => [index + 1, point.timestamp, point.lat, point.lng, point.accuracy ?? '', point.altitude ?? '', point.speed ?? ''])]; return rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n'); }
  $('startBtn').addEventListener('click', start); $('pauseBtn').addEventListener('click', pause); $('exampleBtn').addEventListener('click', addExample); $('clearBtn').addEventListener('click', () => { if (state.points.length && !confirm('¿Borrar el recorrido guardado en este navegador?')) return; pause(); state.points = []; state.activeMs = 0; state.startedAt = null; render(); setStatus('Recorrido borrado.', 'idle'); }); $('geojsonBtn').addEventListener('click', () => state.points.length && download(`track-log-${new Date().toISOString().slice(0, 10)}.geojson`, JSON.stringify(geojson(), null, 2), 'application/geo+json')); $('gpxBtn').addEventListener('click', () => state.points.length && download(`track-log-${new Date().toISOString().slice(0, 10)}.gpx`, gpx(), 'application/gpx+xml')); $('csvBtn').addEventListener('click', () => state.points.length && download(`track-log-${new Date().toISOString().slice(0, 10)}.csv`, csv(), 'text/csv;charset=utf-8')); window.setInterval(() => { if (state.lastStartedAt) render(); }, 1000); initMap(); render();
})();
